build:
	cd sqlite-latest && ./configure --prefix=/workspaces/sqlrsync.com/sqlite_rsync/sqlite-latest/install --enable-static --disable-shared "CFLAGS=-DSQLITE_ENABLE_DBPAGE_VTAB=1 -O2"
clean:
	cd sqlite-latest && make clean
